CREATE TABLE users (id uuid NOT NULL, email varchar(255), password text, name varchar(255), last_name varchar(255), nick_name varchar(255), thumbnail varchar(255), about_me text, created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE animes (id uuid NOT NULL, name text, cover varchar(255), synopsis text, episodes int8, release_date date, finished_date date, background text, otakus_score numeric(5, 2), critics_score numeric(5, 2), created_at timestamp, updated_at timestamp, premiered_id uuid NOT NULL, manga_id uuid NOT NULL, status_id uuid NOT NULL, demographics_d uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE mangas (id uuid NOT NULL, name text, cover varchar(255), synopsis text, volumes int8, chapters int8, release_date date, finished_date date, last_release date, background text, otakus_score numeric(5, 2), critics_score numeric(5, 2), created_at timestamp, updated_at timestamp, state_id uuid NOT NULL, demographic_id uuid NOT NULL, magazine_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE studios (id uuid NOT NULL, name text, description text, established_at date, web_site varchar(255), cover varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE genres (id uuid NOT NULL, name varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE seasons (id uuid NOT NULL, name text, release_date date, finished_date date, created_at timestamp, updated_at timestamp, anime_id uuid NOT NULL, premiered_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE episodes (id uuid NOT NULL, name text, release_date date, score numeric(5, 2), created_at timestamp, updated_at timestamp, season_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE studios_animes (studio_id uuid NOT NULL, anime_id uuid NOT NULL, PRIMARY KEY (studio_id, anime_id));
CREATE TABLE producers (id uuid NOT NULL, name text, description text, established_at date, web_site varchar(255), cover varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE animes_producers (anime_id uuid NOT NULL, producer_id uuid NOT NULL, PRIMARY KEY (anime_id, producer_id));
CREATE TABLE movies (id uuid NOT NULL, name text, release_date date, cover varchar(255), created_at timestamp, updated_at timestamp, anime_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE ovas (id uuid NOT NULL, name text, release_date date, cover varchar(255), created_at timestamp, updated_at timestamp, anime_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE studios_ovas (studio_id uuid NOT NULL, ova_id uuid NOT NULL, PRIMARY KEY (studio_id, ova_id));
CREATE TABLE studios_movies (studio_id uuid NOT NULL, movie_id uuid NOT NULL, PRIMARY KEY (studio_id, movie_id));
CREATE TABLE onas (id uuid NOT NULL, name text, release_date date, cover varchar(255), created_at timestamp, updated_at timestamp, anime_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE studios_onas (studio_id uuid NOT NULL, ona_id uuid NOT NULL, PRIMARY KEY (studio_id, ona_id));
CREATE TABLE producers_movies (producer_id uuid NOT NULL, movie_id uuid NOT NULL, PRIMARY KEY (producer_id, movie_id));
CREATE TABLE producers_ovas (producer_id uuid NOT NULL, ova_id uuid NOT NULL, PRIMARY KEY (producer_id, ova_id));
CREATE TABLE producers_onas (producer_id uuid NOT NULL, ona_id uuid NOT NULL, PRIMARY KEY (producer_id, ona_id));
CREATE TABLE anime_seasons (id uuid NOT NULL, season varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE animes_genres (anime_id uuid NOT NULL, genre_id uuid NOT NULL, PRIMARY KEY (anime_id, genre_id));
CREATE TABLE anime_states (id uuid NOT NULL, status varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE demographics (id uuid NOT NULL, name varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE related_animes (source_id uuid NOT NULL, related_id uuid NOT NULL, PRIMARY KEY (source_id, related_id));
CREATE TABLE characters (id uuid NOT NULL, full_name varchar(255), alias varchar(255), cover varchar(255), description text, created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE animes_characters (anime_id uuid NOT NULL, character_id uuid NOT NULL, role_id uuid NOT NULL, created_at timestamp, updated_at timestamp, PRIMARY KEY (anime_id, character_id));
CREATE TABLE character_roles (id uuid NOT NULL, role varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE songs (id uuid NOT NULL, name text, video_url text, created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE song_types (id uuid NOT NULL, type varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE animes_songs (anime_id uuid NOT NULL, song_id uuid NOT NULL, "order" int4, type_id uuid NOT NULL, PRIMARY KEY (anime_id, song_id));
CREATE TABLE manga_states (id uuid NOT NULL, status varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE mangas_genres (manga_id uuid NOT NULL, genre_id uuid NOT NULL, PRIMARY KEY (manga_id, genre_id));
CREATE TABLE magazines (id uuid NOT NULL, name text, created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE authors (id uuid NOT NULL, name varchar(255), last_name varchar(255), cover varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE mangas_authors (manga_id uuid NOT NULL, author_id uuid NOT NULL, PRIMARY KEY (manga_id, author_id));
CREATE TABLE mangas_characters (manga_id uuid NOT NULL, character_id uuid NOT NULL, role_id uuid NOT NULL, created_at timestamp, updated_at timestamp, PRIMARY KEY (manga_id, character_id));
CREATE TABLE anime_otakus_ratings (user_id uuid NOT NULL, anime_id uuid NOT NULL, comment int4, score numeric(5, 2), created_at timestamp, updated_at timestamp, PRIMARY KEY (user_id, anime_id));
CREATE TABLE anime_critics_ratings (user_id uuid NOT NULL, anime_id uuid NOT NULL, comment int4, score numeric(5, 2), created_at timestamp, updated_at timestamp, PRIMARY KEY (user_id, anime_id));
CREATE TABLE manga_otakus_mangas (user_id uuid NOT NULL, manga_id uuid NOT NULL, comment text, score numeric(5, 2), created_at timestamp, updated_at timestamp, PRIMARY KEY (user_id, manga_id));
CREATE TABLE manga_critics_ratings (user_id uuid NOT NULL, manga_id uuid NOT NULL, comment text, score numeric(5, 2), created_at timestamp, updated_at timestamp, PRIMARY KEY (user_id, manga_id));
CREATE TABLE episodes_ratings (user_id uuid NOT NULL, episode_id uuid NOT NULL, score numeric(5, 2), created_at timestamp, updated_at timestamp, PRIMARY KEY (user_id, episode_id));
CREATE TABLE roles (id uuid NOT NULL, role varchar(255) NOT NULL, created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE roles_users (role_id uuid NOT NULL, user_id uuid NOT NULL, assigned_at timestamp, PRIMARY KEY (role_id, user_id));
CREATE TABLE permissions (id uuid NOT NULL, permission varchar(255) NOT NULL, created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
CREATE TABLE roles_permissions (role_id uuid NOT NULL, permission_id uuid NOT NULL, PRIMARY KEY (role_id, permission_id));
ALTER TABLE studios_animes ADD CONSTRAINT FKstudios_an796571 FOREIGN KEY (studio_id) REFERENCES studios (id);
ALTER TABLE studios_animes ADD CONSTRAINT FKstudios_an389328 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE animes_producers ADD CONSTRAINT FKanimes_pro999107 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE animes_producers ADD CONSTRAINT FKanimes_pro775467 FOREIGN KEY (producer_id) REFERENCES producers (id);
ALTER TABLE studios_ovas ADD CONSTRAINT FKstudios_ov151989 FOREIGN KEY (studio_id) REFERENCES studios (id);
ALTER TABLE studios_ovas ADD CONSTRAINT FKstudios_ov464485 FOREIGN KEY (ova_id) REFERENCES ovas (id);
ALTER TABLE studios_movies ADD CONSTRAINT FKstudios_mo939454 FOREIGN KEY (studio_id) REFERENCES studios (id);
ALTER TABLE studios_movies ADD CONSTRAINT FKstudios_mo980356 FOREIGN KEY (movie_id) REFERENCES movies (id);
ALTER TABLE ovas ADD CONSTRAINT FKovas175715 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE movies ADD CONSTRAINT FKmovies491805 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE onas ADD CONSTRAINT FKonas168027 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE studios_onas ADD CONSTRAINT FKstudios_on159677 FOREIGN KEY (studio_id) REFERENCES studios (id);
ALTER TABLE studios_onas ADD CONSTRAINT FKstudios_on868036 FOREIGN KEY (ona_id) REFERENCES onas (id);
ALTER TABLE producers_movies ADD CONSTRAINT FKproducers_660179 FOREIGN KEY (producer_id) REFERENCES producers (id);
ALTER TABLE producers_movies ADD CONSTRAINT FKproducers_297372 FOREIGN KEY (movie_id) REFERENCES movies (id);
ALTER TABLE producers_ovas ADD CONSTRAINT FKproducers_426034 FOREIGN KEY (producer_id) REFERENCES producers (id);
ALTER TABLE producers_ovas ADD CONSTRAINT FKproducers_848721 FOREIGN KEY (ova_id) REFERENCES ovas (id);
ALTER TABLE producers_onas ADD CONSTRAINT FKproducers_418346 FOREIGN KEY (producer_id) REFERENCES producers (id);
ALTER TABLE producers_onas ADD CONSTRAINT FKproducers_252273 FOREIGN KEY (ona_id) REFERENCES onas (id);
ALTER TABLE animes ADD CONSTRAINT FKanimes75990 FOREIGN KEY (premiered_id) REFERENCES anime_seasons (id);
ALTER TABLE seasons ADD CONSTRAINT FKseasons847071 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE seasons ADD CONSTRAINT FKseasons594229 FOREIGN KEY (premiered_id) REFERENCES anime_seasons (id);
ALTER TABLE episodes ADD CONSTRAINT FKepisodes443483 FOREIGN KEY (season_id) REFERENCES seasons (id);
ALTER TABLE animes ADD CONSTRAINT FKanimes50088 FOREIGN KEY (manga_id) REFERENCES mangas (id);
ALTER TABLE animes_genres ADD CONSTRAINT FKanimes_gen385673 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE animes_genres ADD CONSTRAINT FKanimes_gen326325 FOREIGN KEY (genre_id) REFERENCES genres (id);
ALTER TABLE animes ADD CONSTRAINT FKanimes293585 FOREIGN KEY (status_id) REFERENCES anime_states (id);
ALTER TABLE animes ADD CONSTRAINT FKanimes315010 FOREIGN KEY (demographics_d) REFERENCES demographics (id);
ALTER TABLE related_animes ADD CONSTRAINT FKrelated_an464785 FOREIGN KEY (source_id) REFERENCES animes (id);
ALTER TABLE related_animes ADD CONSTRAINT FKrelated_an766991 FOREIGN KEY (related_id) REFERENCES animes (id);
ALTER TABLE animes_characters ADD CONSTRAINT FKanimes_cha903092 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE animes_characters ADD CONSTRAINT FKanimes_cha624481 FOREIGN KEY (character_id) REFERENCES characters (id);
ALTER TABLE animes_characters ADD CONSTRAINT FKanimes_cha494723 FOREIGN KEY (role_id) REFERENCES character_roles (id);
ALTER TABLE animes_songs ADD CONSTRAINT FKanimes_son912053 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE animes_songs ADD CONSTRAINT FKanimes_son80533 FOREIGN KEY (song_id) REFERENCES songs (id);
ALTER TABLE animes_songs ADD CONSTRAINT FKanimes_son663272 FOREIGN KEY (type_id) REFERENCES song_types (id);
ALTER TABLE mangas ADD CONSTRAINT FKmangas298399 FOREIGN KEY (state_id) REFERENCES manga_states (id);
ALTER TABLE mangas_genres ADD CONSTRAINT FKmangas_gen773801 FOREIGN KEY (manga_id) REFERENCES mangas (id);
ALTER TABLE mangas_genres ADD CONSTRAINT FKmangas_gen522797 FOREIGN KEY (genre_id) REFERENCES genres (id);
ALTER TABLE mangas ADD CONSTRAINT FKmangas988054 FOREIGN KEY (demographic_id) REFERENCES demographics (id);
ALTER TABLE mangas ADD CONSTRAINT FKmangas514327 FOREIGN KEY (magazine_id) REFERENCES magazines (id);
ALTER TABLE mangas_authors ADD CONSTRAINT FKmangas_aut304911 FOREIGN KEY (manga_id) REFERENCES mangas (id);
ALTER TABLE mangas_authors ADD CONSTRAINT FKmangas_aut766703 FOREIGN KEY (author_id) REFERENCES authors (id);
ALTER TABLE mangas_characters ADD CONSTRAINT FKmangas_cha963873 FOREIGN KEY (manga_id) REFERENCES mangas (id);
ALTER TABLE mangas_characters ADD CONSTRAINT FKmangas_cha979099 FOREIGN KEY (character_id) REFERENCES characters (id);
ALTER TABLE mangas_characters ADD CONSTRAINT FKmangas_cha849341 FOREIGN KEY (role_id) REFERENCES character_roles (id);
ALTER TABLE anime_otakus_ratings ADD CONSTRAINT otakus FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE anime_otakus_ratings ADD CONSTRAINT FKanime_otak715190 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE anime_critics_ratings ADD CONSTRAINT critics FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE anime_critics_ratings ADD CONSTRAINT FKanime_crit286401 FOREIGN KEY (anime_id) REFERENCES animes (id);
ALTER TABLE manga_otakus_mangas ADD CONSTRAINT FKmanga_otak444674 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE manga_otakus_mangas ADD CONSTRAINT FKmanga_otak274077 FOREIGN KEY (manga_id) REFERENCES mangas (id);
ALTER TABLE manga_critics_ratings ADD CONSTRAINT FKmanga_crit176300 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE manga_critics_ratings ADD CONSTRAINT FKmanga_crit923460 FOREIGN KEY (manga_id) REFERENCES mangas (id);
ALTER TABLE episodes_ratings ADD CONSTRAINT FKepisodes_r293629 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE episodes_ratings ADD CONSTRAINT FKepisodes_r42279 FOREIGN KEY (episode_id) REFERENCES episodes (id);
ALTER TABLE roles_users ADD CONSTRAINT FKroles_user886729 FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE roles_users ADD CONSTRAINT FKroles_user949729 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE roles_permissions ADD CONSTRAINT FKroles_perm426066 FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE roles_permissions ADD CONSTRAINT FKroles_perm304407 FOREIGN KEY (permission_id) REFERENCES permissions (id);
