ALTER TABLE anime_critics_ratings ALTER COLUMN comment TYPE text;
ALTER TABLE roles_users DROP COLUMN assigned_at;
ALTER TABLE manga_otakus_mangas RENAME TO manga_otakus_ratings;

ALTER TABLE movies DROP CONSTRAINT FKmovies491805;
ALTER TABLE movies ALTER COLUMN anime_id DROP NOT NULL;
ALTER TABLE movies ADD CONSTRAINT FKmovies491805 FOREIGN KEY (anime_id) REFERENCES animes (id);

ALTER TABLE ovas DROP CONSTRAINT FKovas175715;
ALTER TABLE ovas ALTER COLUMN anime_id DROP NOT NULL;
ALTER TABLE ovas ADD CONSTRAINT FKovas175715 FOREIGN KEY (anime_id) REFERENCES animes (id);

ALTER TABLE onas DROP CONSTRAINT FKonas168027;
ALTER TABLE onas ALTER COLUMN anime_id DROP NOT NULL;
ALTER TABLE onas ADD CONSTRAINT FKonas168027 FOREIGN KEY (anime_id) REFERENCES animes (id);

ALTER TABLE mangas RENAME COLUMN state_id TO status_id;

ALTER TABLE animes RENAME COLUMN demographics_d TO demographic_id;

ALTER TABLE animes DROP CONSTRAINT FKanimes75990;
ALTER TABLE animes ALTER COLUMN premiered_id DROP NOT NULL;
ALTER TABLE animes ADD CONSTRAINT FKanimes75990 FOREIGN KEY (premiered_id) REFERENCES japanese_seasons (id);

ALTER TABLE animes DROP CONSTRAINT FKanimes50088;
ALTER TABLE animes ALTER COLUMN manga_id DROP NOT NULL;
ALTER TABLE animes ADD CONSTRAINT FKanimes50088 FOREIGN KEY (manga_id) REFERENCES mangas (id);

